sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-087.pdf --upload --lsstdoc DMTN-087.tex --env=travis --ltd-product dmtn-087"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "VOJDZDWjJbHfyDDrLa4Ufaas1lR0LZGX3lWbxpdVE0wpw4QAtiMb4MYObOVufZorGCHp0CGlh9XxGGUjbiZ2CeL5dVcLQt3nEeER5EQkC/vM7Vjxh+lMMtai8imgoh/Ibx5RnD3m1Bp8Yo8iLVyjlP72DgbMQuE+u/kD+z/YB/lO7519Aizls27OGH7z9QuWnqQi4YirX6gZDup382JXrBqaAsJTYR/PHtrNIR8v0VPbRa3OwNv2BA4SDVbo09Sa/8DvHNOdUZkMuaAamJ7s23TxTFOkcWvuCseZmP19tpXpfKFOR0MH8jkDVZS6spfco8DzSxMXxbu9ScJbeJnoJM+UsB0AlVcR/4ZnirwMYbnInLsqQlcDvRZJeOs1z5DRQ4a+ik72pqhYszGqCD0VZBY2YAIlxG04HXspAU8ppJVUWJDs8cC5zNvzX9chNhqROyxOa4r4NBuafcuoZo+djmM6kInSnajZmesRLH8jOTjg5V8OGsThw8+q/3J9jPLJMmPhY+6Y+iibHbJ7xtf2PIq97FlZ7HJpc7EagqR/gE0Cdb3rKuAd1SvGSuRqhKmMYyX8s8ZrLuo3deX+v4h62Y0Cj+Ja767gPvMPhP2hrsbagAdfV9ZKZoiaYu/bMbnEMvlOINwJYog0QfZn/XweouZvmcFOUaYevhCnBpNgI58="
    - secure: "FEDHBC8eWZcArc+5tV/REW+9eWvWHzyPGe5PY/umZ4TSPmyK/A4/hoPDkcOcyKboMq6vnMtJ3G/j2Q+fx4IHDhJdDklmbsllCTT7Gl3Ua2Bh6CDOP4SlQVPFL/31v672XgOtvTMVnkx9jxUaMpzgt0KynCPcTope+kTvSiGN51jrYons8UrxzP/CTeWtKFfgKi7SVBJnyvyAucNdCmm3U3tcWXJ5BE0raFAm2VgdRdS9w1VJadzyLGO0kcgG8UovkNIxBHZyX9HNd1p/uh9Q+lkuiIcjaq1xoJ68gpDKcds0rxlgkSgwjnWDtvljHOk4848GzRdepcHg7//pWLywwAZK8jSLQxRmiyKZpxmbMnEXoYfTewxrtaOXJ157Vj8MEa0IFpwoc/hAXXEyphBAs3ymPSFS4T48/UedBPBbVB9ntkgvYKQQuEzDDUhSm07lR93rtmoEC+cqsdI9PBEaXHupPY6/iC79cS1mnGiKCAci++sW1wloW8Lx98WEWIJKo0qNGSZidqzRNWnQ5PiP4Xre6q46mc5Dduo+UcZdCC7+ZOjmjOWjaj4lwMcT6iioEbCGfth8ZPEwUCJYBCcPdjIDaaRchtfedtXVC6DN6CyXWc176MKMdug45ZDgpI9cddfIkJ6QBypz5WV8WXp/qcMNP/Dnyz3+SzzPFGcdaTg="
